### ISSUE TITLE
Depend on vega-lib vs. vega?

### ISSUE THREAD

**Issue by gnestor** [vega/vega-embed-v2#3]
We're running into an issue with building canvas using node-gyp and vega-embed-v2 depends on vega which depends on vega-scenegraph which depends on canvas. See our [build log](https://travis-ci.org/jupyterlab/jupyter-renderers/builds/493340690#L1375) for details:

```
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "/home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.9.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v11.9.0/node-v11.9.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v11.9.0/node-v11.9.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v11.9.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v11.9.0/SHASUMS256.txt
gyp info spawn /home/travis/virtualenv/python2.7.14/bin/python2
gyp info spawn args [ '/home/travis/miniconda/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/miniconda/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/.node-gyp/11.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/travis/.node-gyp/11.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/travis/miniconda/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/travis/.node-gyp/11.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function ‘boolean empty_closure_output_buffer(j_compress_ptr)’:
../src/JPEGStream.h:42:108: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, argv);
                                                                                                            ^
../src/JPEGStream.h: In function ‘void term_closure_destination(j_compress_ptr)’:
../src/JPEGStream.h:63:113: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, data_argv);
                                                                                                                 ^
../src/JPEGStream.h:71:112: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, end_argv);
                                                                                                                ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:74:57: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
   if (info[0]->IsNumber()) width = info[0]->Uint32Value();
                                                         ^
../src/Canvas.cc:75:58: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
   if (info[1]->IsNumber()) height = info[1]->Uint32Value();
                                                          ^
../src/Canvas.cc:76:76: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)��� is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2991): Use Isolate version [-Wdeprecated-declarations]
   if (info[2]->IsString()) type = !strcmp(\"pdf\", *String::Utf8Value(info[2]))
                                                                            ^
../src/Canvas.cc:78:48: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2991): Use Isolate version [-Wdeprecated-declarations]
     : !strcmp(\"svg\", *String::Utf8Value(info[2]))
                                                ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Canvas::SetWidth(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../src/Canvas.cc:119:40: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
     canvas->width = value->Uint32Value();
                                        ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Canvas::SetHeight(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../src/Canvas.cc:140:41: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
     canvas->height = value->Uint32Value();
                                         ^
../src/Canvas.cc: In static member function ‘static void Canvas::ToBufferAsyncAfter(uv_work_t*)’:
../src/Canvas.cc:221:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     closure->pfn->Call(1, argv);
                               ^
../src/Canvas.cc:226:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     closure->pfn->Call(2, argv);
                               ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:274:52: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
           compression_level = info[1]->Uint32Value();
                                                    ^
../src/Canvas.cc:279:49: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
             uint32_t tmp = info[1]->Uint32Value();
                                                 ^
../src/Canvas.cc:301:39: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
         filter = info[2]->Uint32Value();
                                       ^
../src/Canvas.cc: In function ‘cairo_status_t streamPNG(void*, const uint8_t*, unsigned int)’:
../src/Canvas.cc:377:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure->fn, 3, argv);
                                                                                                      ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:396:52: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
           compression_level = info[1]->Uint32Value();
                                                    ^
../src/Canvas.cc:401:49: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
             uint32_t tmp = info[1]->Uint32Value();
                                                 ^
../src/Canvas.cc:423:39: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2571): Use maybe version [-Wdeprecated-declarations]
         filter = info[2]->Uint32Value();
                                       ^
../src/Canvas.cc:446:103: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);
                                                                                                       ^
../src/Canvas.cc:452:103: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);
                                                                                                       ^
../src/Canvas.cc: In function ‘cairo_status_t streamPDF(void*, const uint8_t*, unsigned int)’:
../src/Canvas.cc:476:77: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../nan/nan.h:959) [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), closure->fn, 3, argv);
                                                                             ^
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamJPEGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:557:64: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
   write_to_jpeg_stream(canvas->surface(), info[0]->NumberValue(), info[1]->NumberValue(), info[2]->BooleanValue(), &closure);
                                                                ^
../src/Canvas.cc:557:88: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
   write_to_jpeg_stream(canvas->surface(), info[0]->NumberValue(), info[1]->NumberValue(), info[2]->BooleanValue(), &closure);
                                                                                        ^
../src/Canvas.cc:557:113: warning: ‘bool v8::Value::BooleanValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2568): Use maybe version [-Wdeprecated-declarations]
   write_to_jpeg_stream(canvas->surface(), info[0]->NumberValue(), info[1]->NumberValue(), info[2]->BooleanValue(), &closure);
                                                                                                                 ^
../src/Canvas.cc: In member function ‘void Canvas::resurface(v8::Local<v8::Object>)’:
../src/Canvas.cc:641:85: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:10254): Use maybe version [-Wdeprecated-declarations]
         Context2d *context2d = Nan::ObjectWrap::Unwrap<Context2d>(context->ToObject());
                                                                                     ^
../src/Canvas.cc:657:85: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:10254): Use maybe version [-Wdeprecated-declarations]
         Context2d *context2d = Nan::ObjectWrap::Unwrap<Context2d>(context->ToObject());
                                                                                     ^
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
../src/CanvasGradient.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gradient::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/CanvasGradient.cc:45:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
         info[0]->NumberValue()
                              ^
../src/CanvasGradient.cc:46:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[1]->NumberValue()
                              ^
../src/CanvasGradient.cc:47:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[2]->NumberValue()
                              ^
../src/CanvasGradient.cc:48:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[3]->NumberValue());
                              ^
../src/CanvasGradient.cc:57:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
         info[0]->NumberValue()
                              ^
../src/CanvasGradient.cc:58:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[1]->NumberValue()
                              ^
../src/CanvasGradient.cc:59:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[2]->NumberValue()
                              ^
../src/CanvasGradient.cc:60:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[3]->NumberValue()
                              ^
../src/CanvasGradient.cc:61:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[4]->NumberValue()
                              ^
../src/CanvasGradient.cc:62:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[5]->NumberValue());
                              ^
../src/CanvasGradient.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Gradient::AddColorStop(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/CanvasGradient.cc:83:32: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2991): Use Isolate version [-Wdeprecated-declarations]
   String::Utf8Value str(info[1]);
                                ^
../src/CanvasGradient.cc:90:30: warning: ‘double v8::Value::NumberValue() const’ is deprecated (declared at /home/travis/.node-gyp/11.9.0/include/node/v8.h:2569): Use maybe version [-Wdeprecated-declarations]
       , info[0]->NumberValue()
                              ^
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
In file included from ../src/CanvasPattern.cc:9:0:
../src/Image.h:19:21: fatal error: gif_lib.h: No such file or directory
 #include <gif_lib.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
make: Leaving directory `/home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/miniconda/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command \"/home/travis/miniconda/bin/node\" \"/home/travis/miniconda/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/travis/miniconda/share/jupyter/lab/staging/node_modules/canvas
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

According to https://github.com/vega/vega/issues/1073, [vega-lib](https://github.com/vega/vega-lib) is vega minus optional dependencies. Should vega-embed-v2 depend on vega-lib vs. vega? I'm not sure if there is a vega 2 version of vega-lib...

**Comment by jheer** [comment]
**As of Vega v5, `vega-lib` is being discontinued.** Instead you can depend on Vega v5+ directly without a Canvas dependency. Moreover, we've updated to the latest major version of Canvas, which has a more friendly build process and fallbacks should you want to include canvas for server-side use.

Vega 5.0.0-rc1 has been released. More releases to follow soon!

**Comment by domoritz** [comment]
Note that this is vega-embed for Vega 2! Vega-Lib did not exist for Vega 2.

**Comment by jheer** [comment]
Also, for older Vega versions (v1 or v2), vega-lib is not available -- it was added with Vega 3+.

**Comment by gnestor** [comment]
Ok, so no recommendations for working around this error?

**Comment by domoritz** [comment]
You can ignore the error. Canvas is not needed. I know it's not great but I don't know any other workarounds for Vega 2.

**Comment by jheer** [comment]
@domoritz is correct. Another (more involved) solution would be to modify the old Vega code and make a new v2 maintenance release.

**Comment by gnestor** [comment]
Ok, it's not a biggie since most people are not using vega2 or @jupyterlab/vega2-extension, but we do see that error everytime we run the build 🤷‍♂️
